#
#  ansible/sample.yml - demo of ansible tasks that make no changes
#
#  No need to use `-C` because it changes nothing.
#  Run with `-v` to see details about the return values,
#  and `-vvv` to see the connection information.
#
---
- hosts: vagrant
  vars:
      ls_dir: /vagrant
  roles:
    - template-role             # roles always run before loose tasks
  tasks:
    - name: ping
      ping:
    - name: id
      command: id
    - name: ls
      command: ls {{ls_dir}}
