---
- hosts: vagrant
  remote_user: bogus        # Login user; appears to have no effect?!
  become: yes               # becomes root (become_user changes this)
  roles:
    - geerlingguy.repo-epel
    - officel.etckeeper     # needs EPEL, brings in Git
